version: "3"

services:
  jenkins:
    image: jenkins/jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  sonarqube:
    image: sonarqube:8.5.1-community
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - 9000:9000
    networks:
      - jenkins      
    environment:
      - sonar.jdbc.username=admin
      - sonar.jdbc.password=admin
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - ./logs:/opt/sonarqube/logs
      - ./data:/opt/sonarqube/data
      - ./extensions:/opt/sonarqube/extensions

  db:
    image: postgres:13.1
    container_name: db
    hostname: db
    networks:
      - jenkins
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./pg_db:/var/lib/postgresql
      - ./pg_data:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  pg_db:
    driver: local
  pg_data:
    driver: local

networks:
  jenkins:    